CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_ZEPHYR_NUS=y
CONFIG_BT_DEVICE_NAME="NUS simple demo"
CONFIG_BT_L2CAP_TX_MTU=104
CONFIG_BT_BUF_ACL_RX_SIZE=108
CONFIG_BT_BUF_ACL_TX_SIZE=108
CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_DEBUG=n