CONFIG_BT=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_CREATE_CONN_TIMEOUT=10



CONFIG_BT_GATT_CLIENT=y

# Enable the BLE modules from NCS
CONFIG_BT_NUS_CLIENT=y

CONFIG_BT_GATT_DM=y
#CONFIG_HEAP_MEM_POOL_SIZE=2048
CONFIG_SIZE_OPTIMIZATIONS=y